version: "3.8"

services:
  # --- 1. DATABASE SERVICE ---
  db_service:
    image: mysql:8.0
    # GANTI NAMA: Tambahkan _menfess
    container_name: db_menfess_${GROUP_NAME}
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      # GANTI LOGICAL VOLUME
      - db_data_menfess:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tekser-network

  # --- 2. APP SERVICE ---
  app_service:
    build: ./app
    # GANTI NAMA
    container_name: app_menfess_${GROUP_NAME}
    restart: always
    expose:
      - "3000"
    environment:
      - DB_HOST=db_service
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - APP_PORT=3000
    depends_on:
      - db_service
    networks:
      - tekser-network

  # --- 3. NGINX SERVICE ---
  nginx_service:
    image: nginx:alpine
    # GANTI NAMA
    container_name: nginx_menfess_${GROUP_NAME}
    restart: always
    ports:
      # GANTI PORT: Pakai 8080 (Biar SimKos tetap jalan di 2584)
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_service
    networks:
      - tekser-network

#--- VOLUMES DEFINITION (BAGIAN INI YANG BIKIN BENTROK KEMARIN) ---
volumes:
  db_data_menfess: # Nama Logical (Harus sama dengan di db_service)
    name: mysql_data_menfess_${GROUP_NAME} # Nama Fisik (Harus BEDA dengan SimKos)
    driver: local

networks:
  tekser-network:
    driver: bridge
    name: net_tekser_menfess_${GROUP_NAME}